# Fly.io配置文件
app = "telegram-reminder-bot"
primary_region = "nrt"  # 东京节点，延迟较低

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[deploy]
  release_command = "echo 'Deployment complete'"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256